services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev_mem
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d dev_mem" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - type: bind
        source: "${POSTGRES_DATA_DIR:-./data/postgres}"
        target: /var/lib/postgresql/data
    networks:
      - default
    ports:
      - "${POSTGRES_PORT:-45533}:5432"

networks:
  default:
    driver: bridge
